name: Tag and push to PyPI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          architecture: "x64"
          cache: pip

      - name: Acquire version
        run: |
          echo "PACKAGE_VERSION=$(python scripts/get_version.py -p v)" >> $GITHUB_ENV

      - name: Create Git tag
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GH_ACTION_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ env.PACKAGE_VERSION }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: ""

      - name: Install tox
        run: |
          pip install -r requirements-min.txt

      - name: Create distribution
        run: |
          tox -e build

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
