name: Test building python packages

on:
  push:
    branches: ["main", "feature/**", "hotfix/**"]
  pull_request:
    types: [opened, reopened]
    branches: ["*"]
  workflow_dispatch: {}

jobs:
  python_test_suite:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      max-parallel: 4
      fail-fast: false

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-python@v3
        with:
          python-version: "3.7"
          architecture: "x64"
          cache: pip

      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          architecture: "x64"
          cache: pip

      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          architecture: "x64"
          cache: pip

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: "x64"
          cache: pip

      - run: python -m pip install tox

      - run: tox -e build-py37 -vv
      - run: tox -e build-py38 -vv
      - run: tox -e build-py39 -vv
      - run: tox -e build-py310 -vv
